spring.application.name=API-GATEWAY

server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=transport-service
spring.cloud.gateway.routes[0].uri=lb://TRANSPORT
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/**

management.endpoints.web.exposure.include=*